database:
  type: mysql
  host: 111.231.228.108
  port: 4446
  user: root
  password: mwltest
  databasename: oauth2-server
  maxidleconns: 5
  maxopenconns: 5
oauth:
  accesstokenlifetime: 3600
  refreshtokenlifetime: 1209600
  authcodelifetime: 3600
session:
  secret: test_secret
  path: /
  maxage: 604800
  httponly: True
serverport: 3001
isdev: True
redis:
  host: 111.231.228.108
  port: 6379
  password:
  maxidleconns: 10